language: r
pandoc_version: 1.19
cache: 
  packages: yes
  directories:
    - $HOME/bin

branches:
  only:
    - master

env:
  global:
    - secure: "LLtJXOiTNpZh2pJ0+eiaxzpzWY0uOXPYJRaj61PQVNXjANg/n8czMJgjNPKuuLv3EeK8e4Nn1jQ1yU3w3Rj+ZcDpQhEH91v19x13T8jQ1L1W1dcLJJtTF8Xos5Id2aDVy78pPSI7y59Dv5sv7oe6FCGZbCH3zwT/tEZYXteRDpzd9HTtYlpuO4uNoiuWApU8k/hXYNe863i8XJ+2eXVb7HU6zDlqsfx227nBy/eMpL12lCtka4SoTNvTbmSi/Z6WXT1Eve9r3Qr9VLxeiNsoT+wpa2BOTNvs+2UgFFoVeQ+cdnLntPp+4xV3uZZH1y0pDSe/PrqxNrS/Y9MM2Z2Tbbvgjiofdhghor47y2KrURbX86lhSFosSBGC3H6AJmpp/fQbov6Cxx91xL6uZC86+SFplvnkBFZUwIuRM2iSgDXiAiqFpxBq8IPvcyfiKnDDmeXpfB4Lxl4kDqVdyppXLM0MkiekZBg2pMKJwzqHTKOpfWLfew2M43cXcZRuTfJ7oWywNgY1beaKDRqWjTp+hHDYSnalnxLKp1A0c7t5kjqLdQ4CErJYswjYcDyEpgNKrWXO2jsFcVpNuusBrXrOGSJknOrr4FnN4GFCytlOBN8NoFZJiI3mpXFWgf2MdV6zkJjFJW8Ch9pDrsSdP2RRybbuOObwLGfY2hDvUdzVJjE="

before_script:
  - Rscript -e "update.packages(.libPaths()[1], ask = FALSE)"
  - "[ -x \"$HOME/bin/hugo\" ] || Rscript -e \"blogdown::install_hugo()\""
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
