name: Kenji Sato
sitename: kenjisato.jp
bio: 'Kobe University'
picture: 'assets/images/me.jpg'

url: http://www.kenjisato.jp
baseurl: /
permalink: /:title/

analytics: 'UA-8443903-1'
disqus: kenjisatojp
facebook: kenjisato.jp
github: kenjisato
gplus: KenjiSato1983
email: mail@kenjisato.jp

exclude: [README.md, Gemfile, Gemfile.lock, node_modules,
          gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

markdown: kramdown
syntax_highlighter: coderay
