[context.production.environment]
  HUGO_VERSION = "0.108.0"

[context.deploy-preview]
  command = "hugo --buildFuture --buildDrafts"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.108.0"

[context.branch-deploy]
  command = "hugo --buildFuture --buildDrafts"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.108.0"
    